FROM ruby:2.6.5-slim-buster AS ruby

FROM debian:buster-slim

RUN mkdir -p /opt/ruby/bin /opt/ruby/lib /opt/ruby/include

COPY --from=ruby /usr/local/bin /usr/local/bin
COPY --from=ruby /usr/local/lib /usr/local/lib
COPY --from=ruby /usr/local/include /usr/local/include

RUN gem install parse_fasta

WORKDIR /root
